alias: Livingroom lights on before sunrise
trigger:
  platform: sun
  event: sunrise
  offset: "-01:15:00"
action:
  - service: mqtt.publish
    data:
      topic: "/home/floor/1/livingroom/outlets/1"
      payload: "1"
      retain: true
  - service: mqtt.publish
    data:
      topic: "/home/floor/1/livingroom/outlets/3"
      payload: "1"
      retain: true
  - service: mqtt.publish
    data:
      topic: "/home/floor/1/livingroom/outlets/4"
      payload: "1"
      retain: true
