alias: Livingroom lights off at bedtime 
trigger:
  platform: time
  at: "22:15:00"
action:
  - service: mqtt.publish
    data:
      topic: "/home/floor/1/livingroom/outlets/1"
      payload: "0"
      retain: true
  - service: mqtt.publish
    data:
      topic: "/home/floor/1/livingroom/outlets/3"
      payload: "0"
      retain: true
  - service: mqtt.publish
    data:
      topic: "/home/floor/1/livingroom/outlets/4"
      payload: "0"
      retain: true
